export const Actions = {
  SUBMIT_GUESS: 'SUBMIT_GUESS',
  START: 'START',
  ADD_LETTER: 'ADD_LETTER',
  REMOVE_LETTER: 'REMOVE_LETTER',
  UPDATE_KEY_COLOR: 'UPDATE_KEY_COLOR',
  FLIP_TILE: 'FLIP_TILE',
  GAME_OVER_LOSS: 'LOSS',
  GAME_OVER_WIN: 'WIN',
};
